=== ssi-schaefer/ccmtools/ccmtools/test/Deployment/Metamodel/deployment.dtd
<?xml encoding="UTF-8" ?>

<!-- ComponentPackageDescription DTD -->

<!-- A component has an interface composed of operations, attributes and ports
	 that may be connected to other components.
	 A component may have a concrete (monolithic) implementation contained in an
	 artifact, or it may be recursively implemented by an assembly (a set of
     interconnected subcomponents. -->

<!-- Describes multiple alternative implementations of the same component 
     interface -->     
<!ELEMENT ComponentPackageDescription 
( 
	ComponentInterfaceDescription?,
	PackagedComponentImplementation+
)>
<!ATTLIST ComponentPackageDescription
	label CDATA #IMPLIED
	UUID CDATA #IMPLIED
>	


<!-- Dscribes a component's interface. Ideally, a ComponentInterfaceDescription 
	 can be generated from component IDL files. -->
<!ELEMENT ComponentInterfaceDescription 
( 
	SupportedType+,
	IdlFile*
)>
<!-- specificType: The most specific type supported by this component.-->
<!ATTLIST ComponentInterfaceDescription
	label CDATA #IMPLIED
	UUID CDATA #IMPLIED
	specificType CDATA #REQUIRED
>	


<!-- Assign names to alternative ComponentImplementationDescription 
	 elements within a package-->
<!ELEMENT PackagedComponentImplementation 
( 
	ComponentImplementationDescription,
)>
<!-- name: Name assigned to this implementation (registered at the 
	       HomeFinder Singleton). -->
<!ATTLIST PackagedComponentImplementation
	name CDATA #REQUIRED
>	

<!-- Describes a specific implementation of a component interface 
	 which can be either assembly based or monolithic. -->
<!ELEMENT ComponentImplementationDescription 
( 
	ComponentAssemblyDescription?,
	MonolithicImplementationDescription?
)>
<!ATTLIST ComponentImplementationDescription
	label CDATA #IMPLIED
	UUID CDATA #IMPLIED
>


<!-- Contains information about sub-component instances, 
	 connections among ports. -->
<!ELEMENT ComponentAssemblyDescription 
( 
	ComponentAssemblyArtifactDescription+
)>

<!-- This is a CCM-Tools extension to the deployment model to 
	 support native language assembly objects. -->
<!ELEMENT ComponentAssemblyArtifactDescription 
( 
	Location+
)>
<!-- specificType: Name of the assembly object's implementation class. -->
<!ATTLIST ComponentAssemblyArtifactDescription
	label CDATA #IMPLIED
	UUID CDATA #IMPLIED
	specificType CDATA #REQUIRED	
>

<!-- Describes the artifacts that are involved in this component 
	 implementation.
  	 It references primary implementation artifacts. -->
<!ELEMENT MonolithicImplementationDescription 
( 
	NamedImplementationArtifact+
)>

<!-- Used to assign names to primary implementation artifacts.-->
<!ELEMENT NamedImplementationArtifact 
( 
	ImplementationArtifactDescription
)>
	<!-- The assigned name to this implementation artifact. -->
<!ATTLIST NamedImplementationArtifact
	name CDATA #REQUIRED
>


<!-- Describes an implementation artifact that is associated 
	 with a monolithic component implementation. -->
<!ELEMENT ImplementationArtifactDescription 
( 
	Location+
)>
<!ATTLIST ImplementationArtifactDescription
	label CDATA #IMPLIED
	UUID CDATA #IMPLIED
>


<!-- The location of the implementation artifacts. -->
<!ELEMENT Location 
( 
	#PCDATA 
)>


<!-- Lists the RepositoryID of provided, used and supported interfaces. -->
<!ELEMENT SupportedType 
( 
	#PCDATA 
)>


<!-- UIRs that reference an IDL File containing component's interface 
	 definition. -->
<!ELEMENT IdlFile 
( 
	#PCDATA 
)>

=== ssi-schaefer/ccmtools/ccmtools/test/Deployment/Metamodel/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ComponentPackageDescription SYSTEM "deployment.dtd">

<ComponentPackageDescription label="" UUID="">
   <ComponentInterfaceDescription label="" UUID="" specificType="IDL:wamas/stocktake/MainHome:1.0">
      <SupportedType>IDL:wamas/stocktake/MainHome:1.0</SupportedType>
      <SupportedType>IDL:wamas/stocktake/Main:1.0</SupportedType>
      <IdlFile>wamas/stocktake/MainHome.idl</IdlFile>
      <IdlFile>wamas/stocktake/Main.idl</IdlFile>
   </ComponentInterfaceDescription>
   <PackagedComponentImplementation name="myMainHome">
      <ComponentImplementationDescription label="" UUID="">
         <ComponentAssemblyDescription>
            <ComponentAssemblyArtifactDescription label="" UUID="" specificType="IDL:wamas/stocktake/StocktakeAssembly:1.0">
               <Location>wamas/stocktake/assembly/stocktake_assembly.h</Location>
            </ComponentAssemblyArtifactDescription>
         </ComponentAssemblyDescription>
         <MonolithicImplementationDescription>
            <NamedImplementationArtifact name="xy">
               <ImplementationArtifactDescription label="" UUID="">
                  <Location>xy.h</Location>
                  <Location>xy.cc</Location>
               </ImplementationArtifactDescription>
            </NamedImplementationArtifact>
         </MonolithicImplementationDescription>
      </ComponentImplementationDescription>
   </PackagedComponentImplementation>
</ComponentPackageDescription>
